name: Publish Docker image
on:
  push:
    branches:
      - master
jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}:latest
          cache-from: type=registry,ref=${{ github.repository }}:builder

      - name: Save build cache
        uses: docker/build-push-action@v2
        with:
          target: builder
          build-args: BUILDKIT_INLINE_CACHE=1
          push: true
          tags: ${{ github.repository }}:builder
